// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://svtxsazfjxfvnmttorju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dHhzYXpmanhmdm5tdHRvcmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODI4ODUsImV4cCI6MjA1NjQ1ODg4NX0.8ZHpam8BK0PL4NZoF_xZ8UsKsmHo04Qxj0GUSvnHmus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);